<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5iZ2mlp\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5iZ2mlp/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container5iZ2mlp.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container5iZ2mlp\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container5iZ2mlp\appAppKernelProdContainer([
    'container.build_hash' => '5iZ2mlp',
    'container.build_id' => 'e467dd5c',
    'container.build_time' => 1767621013,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5iZ2mlp');
