<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Core\Security\TokenAuthenticator' shared service.

return $this->privates['PrestaShop\\PrestaShop\\Core\\Security\\TokenAuthenticator'] = new \PrestaShop\PrestaShop\Core\Security\TokenAuthenticator(new \PrestaShopBundle\Security\OAuth2\ResourceServer(new \League\OAuth2\Server\ResourceServer(($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] ?? ($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] = new \PrestaShopBundle\Security\OAuth2\Repository\AccessTokenRepository())), new \League\OAuth2\Server\CryptKey('-----BEGIN PUBLIC KEY-----'."\n".'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsoeABxcXlWiVpRT9nHNO'."\n".'lkcS1A+Xdr3VnykS2sMMCHAQUUc4bLusi6QfHZ1TjDF/rm5rEHSjdqoxY+3u3s1Z'."\n".'5BVUvfnUczDTt9Z9ePJiLxTQHO0j7LG5sPZHPMpNgG3CfZ3hHmLtfxjz/me+AeG4'."\n".'ZgQDRsR9pOwwAzL4gKfWuJfV+b9+A8MJgrfobrQAzG57DMfAijkVaC/tD/WqKyle'."\n".'yy/o2Q38XUCzLrui0T7FRoDtLzl7nbCmOJZbjDyHN+N9WcPhxCoXKRAkT2I1Oywj'."\n".'ZnWWJTTqNn44CFM4Mbr/Ll8aZGx3aR4L89ZN2xfkppGJMukHf1IBIjoEm4mfdosa'."\n".'EQIDAQAB'."\n".'-----END PUBLIC KEY-----'."\n".'')), ($this->privates['security.user.provider.concrete.oauth2'] ?? ($this->privates['security.user.provider.concrete.oauth2'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider([])))), ($this->privates['Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory'] ?? $this->load('getPsrHttpFactoryService.php')));
