<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3mT8IUW\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3mT8IUW/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3mT8IUW.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\Container3mT8IUW\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \Container3mT8IUW\appAppKernelDevDebugContainer([
    'container.build_hash' => '3mT8IUW',
    'container.build_id' => 'a8e86282',
    'container.build_time' => 1767620994,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3mT8IUW');
